Algoritmo "Vetores"
//  
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 19/03/2024
Var
// Seção de Declarações das variáveis 

v:vetor[1..5] de inteiro
Cont: inteiro
Inicio

para cont de 1 ate 5 faca
escreval("Digite um numero")
leia(v[cont])
fimpara

Para cont de 1 ate 5 faca
Escreval (V[cont])
fimpara

Fimalgoritmo